### ISSUE TITLE
[Outlook Web][Rendering] Markdown pushing links onto new line

### ISSUE THREAD

**Issue by cbdabner** [microsoft/AdaptiveCards#5701]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] Outlook Web Client

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

Author

# Details

A recent update (last few days?) to Outlook for Web looks to be rendering markdown in cards incorrectly. All links are pushed onto their own line.

Dev Tools shows:
```css
.ac-anchor {
  text-decoration: none;
  display: inline-block;
  width: 100%; /* <-- problem? */
}
```

**Exampe screenshot:**

![screenshot](https://user-images.githubusercontent.com/9081012/115486024-263a8f00-a299-11eb-9d20-e2c0b78c6e8e.png)
